apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  project: default
  source:
    repoURL: https://github.com/ftathiago/raspi-argocd.git
    path: keycloak
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true